arm/trusted-firmware-a: disable -Werror
-Werror is typically a bad idea in distribution builds, as changes to
the compiler or other libraries can cause new warnings to appear.

For example, when building the N1SDP platform:

  error: "GIC-600 Multichip driver is currently experimental and the API
          may change in future." [-Werror,-W#warnings]

Set E=0 so that -Werror is not used in the build.

Change-Id: I8905fc9d4e95edb42970fe3839b9ab6b5384a123
Signed-off-by: Ross Burton <ross.burton@arm.com>
Signed-off-by: Jon Mason <jon.mason@arm.com>