arm-bsp/edk2-firmware: fix build on newer hosts
Compiles of edk2-firmware with GCC 15 on the host will fail:

main.c: In function ‘ProcessArgs’:
| main.c:163:42: error: too many arguments to function ‘p->process’; expected 0, have 2
|   163 |                                         (*p->process)( *argv, *(argv+1) );
|       |                                         ~^~~~~~~~~~~~  ~~~~~

We actually already had the fix for this, but were doing SRC_URI +=
_before_ the include file did SRC_URI =, so the patch was never applied.

Move the require to the top of the recipe so this ordering problem does
not happen, and fix the line-endings in the patch that never got applied.

[ YOCTO #16116 ]

Signed-off-by: Ross Burton <ross.burton@arm.com>
Signed-off-by: Jon Mason <jon.mason@arm.com>