arm/edk2-firmware: unbreak builds with latest Clang
The latest Clang produced unaligned access warnings, which EDK2 promotes
to errors with -Werror.

  edk2/MdeModulePkg/Include/Guid/ExtendedFirmwarePerformance.h:78:47:
  error: field Guid within 'FPDT_GUID_EVENT_RECORD' is less aligned than 'EFI_GUID'
  and is usually due to 'FPDT_GUID_EVENT_RECORD' being packed, which can lead to
  unaligned accesses [-Werror,-Wunaligned-access]

This has been reported upstream so for now ignore this warning.

Signed-off-by: Ross Burton <ross.burton@arm.com>